### ISSUE TITLE
alt-src should log exit code when command fails

### ISSUE THREAD

**Issue by rohanpm** [release-engineering/alt-src#19]
Currently, when alt-src runs a command and it fails, the exit code of the command is never logged:

```
# in log_cmd

        for i in range(1, tries+1):
            proc = subprocess.Popen(cmd, **kwargs)
            ret = proc.wait()
            if not ret:
                return ret
            elif ret and i < tries:
                sleep_time = i * 30
                fmt = ' Command %s failed, will retry in %ss [tried: %s/%s]'
                self.logger.warn(fmt, ' '.join(cmd), sleep_time, i, tries)
                time.sleep(sleep_time)
        if ret:
            if fatal:
                raise CommandError, "command failed: %r" % cmd
            #otherwise
            self.logger.warn("Command failed: %r", cmd)
        return ret
```

See that `ret` is not included in the log messages here.  (The callers of log_cmd also don't log it.)

It would be better if the exit code was logged here.  Many tools communicate useful info through their exit codes, which can be useful in debugging failures.  For example, see "man rsync" where the meaning of each exit code is listed.

**Comment by rbikar** [comment]
Released in  https://github.com/release-engineering/alt-src/releases/tag/v1.3.0
