### ISSUE TITLE
Build/CI fails with koji v1.20 due to missing dependency on rpm-py-installer

### ISSUE THREAD

**Issue by rajulkumar** [release-engineering/alt-src#22]
Build/CI fails when alt-src package is installed with koji 1.20. Koji with it's new version made the dependency on rpm-py-installer optional. However, it requires the package to run without crashes as below.
```
Traceback (most recent call last):
  File "/home/rajkumar/Projects/alt-src/alt_src/alt_src.py", line 2100, in main
    task.run()
  File "/home/rajkumar/Projects/alt-src/alt_src/alt_src.py", line 657, in run
    self.read_source_file()
  File "/home/rajkumar/Projects/alt-src/alt_src/alt_src.py", line 314, in read_source_file
    self.read_srpm()
  File "/home/rajkumar/Projects/alt-src/alt_src/alt_src.py", line 336, in read_srpm
    headers = koji.get_rpm_header(self.source_file)
  File "/home/rajkumar/Projects/alt-src/.tox/py27/lib/python2.7/site-packages/koji/__init__.py", line 908, in get_rpm_header
    ts = rpm.TransactionSet()
AttributeError: 'module' object has no attribute 'TransactionSet'
```

The package rpm-py-installer was added as dependency in test-requirements.txt which helps to run the CI. 
However, this should work with newer koji packages without any explicit dependency inclusions.

**Comment by rbikar** [comment]
@rajulkumar 
You may want to check https://github.com/release-engineering/ubi-population-tool/pull/110/files 
where we solved the same thing I guess. 
Also note that it requires little hack in spec file for alt-src, see Q6 at https://github.com/junaruga/rpm-py-installer/blob/master/docs/users_guide.md 
or check spec file of ubipop how it was practically solved.

**Comment by rohanpm** [comment]
> However, this should work with newer koji packages without any explicit dependency inclusions.

Does this mean that you'd consider the current rpm-py-installer presence in test-requirements.txt as a bug which ideally should be removed?  i.e. koji should be fixed instead?

Not sure I agree with that.  There is definitely the concept of an optional requirement and koji isn't required to support everything as part of its default installation.  In other words I don't think this koji behavior is necessarily a bug (well, ideally the exception it was raising would be friendlier).

Plenty of other Python packages have this kind of thing as well.  e.g. see gunicorn, http://docs.gunicorn.org/en/latest/install.html.  If you installed gunicorn only and didn't install one of the add-on packages like gunicorn[eventlet], you will get crashes if you try to use certain features.

**Comment by rajulkumar** [comment]
@rbikar @rohanpm 
Can we say that https://github.com/release-engineering/alt-src/commit/9924dcdaab3b524f6aac5bb15a36b9f0a519af6f resolves this issue?

**Comment by rohanpm** [comment]
@rajulkumar sure.

**Comment by rajulkumar** [comment]
Fixed as https://github.com/release-engineering/alt-src/commit/9924dcdaab3b524f6aac5bb15a36b9f0a519af6f in PR https://github.com/release-engineering/alt-src/pull/24
