### ISSUE TITLE
Some packages have no SOURCES directory, alt-src throws OSError

### ISSUE THREAD

**Issue by bstinsonmhk** [release-engineering/alt-src#27]
When we upload to the lookaside alt-src looks inside the SOURCES directory for any tarballs: 
https://github.com/release-engineering/alt-src/blob/68d6ba5e05f4df65104316637618c933d15c3438/alt_src/alt_src.py#L945

Some packages don't have a SOURCES directory, though, and we should just continue the push without uploading anything to the lookaside. Currently running alt-src on a package like this results in 
`OSError: [Errno 2] No such file or directory'

**Comment by rohanpm** [comment]
@bstinsonmhk would you mind pointing to an example RPM which can trigger this?

**Comment by rohanpm** [comment]
I happened to discover that *no* SRPMs actually include a `SOURCES` directory, the creation of that directory is instead a behavior of the rpm command during installation.  The `.spec` file is put into `SPECS`, while every other file is put into `SOURCES`.

So, I suppose the case which triggers this is an RPM which contains only a `.spec` file and nothing else.

**Comment by rohanpm** [comment]
This is thought to be fixed in v1.5.0.
